account/urls.py
from django.conf.urls import url
#from django.contrib.auth.views import login
from . import views
from django.urls import path

app_name='account'
urlpatterns = [
path('', views.home),
path('loginL/',views.login_L,name='login_L'),
path('signupL/',views.signup_L,name='signup_L'),
path('signupE/',views.signup_E,name='signup_E'),
path('loginE/',views.login_E,name='login_E'),
path('signupL/detL/',views.detL,name='detL'),
path('signupE/detE/',views.detE,name='detE'),
path('loginE/dashE/',views.dashE,name='dashE'),
path('loginL/dashL/',views.dashL,name='dashL'),
path('loginE/dashE/find/<name>',views.find,name='find'),
path('feed/', views.FeedViewSet),
path('save/', views.saveData),
]

test3/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

account/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
import datetime
from django.db import models
import psycopg2

class Labours(models.Model):
    l_name=models.CharField(max_length=70)
    l_con_no=models.CharField(max_length=10)
    l_pass=models.CharField(max_length=20)
    l_id_no=models.CharField(max_length=50)
    l_addr=models.CharField(max_length=100)
    pres=models.IntegerField(default=0)

class Employers(models.Model):
    e_name=models.CharField(max_length=70)
    e_con_no=models.CharField(max_length=10)
    e_mail=models.CharField(max_length=50)
    e_pass=models.CharField(max_length=20)
    e_id_no=models.CharField(max_length=50)

class Feed(models.Model):
    e_con_no=models.CharField(max_length=10)
    l_con_no=models.CharField(max_length=10)
    comment=models.CharField(max_length=500)

account/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import get_object_or_404,render_to_response,render
from django.urls import reverse
from .models import Labours,Employers,Feed
import json
from rest_framework import viewsets
from .serializers import FeedSerializer
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def home(request):
    return render(request, 'structure/home.html')

def signup_L(request):
    return render(request, 'structure/signup_Labour.html')

def login_L(request):
    return render(request, 'structure/login_Labour.html')

def signup_E(request):
    return render(request, 'structure/signup_Employer.html')

def login_E(request):
    return render(request, 'structure/login_Emp.html')

def detL(request):
    name=request.POST['sname']
    con=request.POST['pnum']
    pass1=request.POST['pass1']
    id_no=request.POST['id_no']
    addr=request.POST['addr']
    q=Labours(l_name=request.POST['sname'],l_con_no=request.POST['pnum'],l_pass=request.POST['pass1'],l_id_no=request.POST['id_no'],l_addr=addr)
    q.save()
    return render(request,'structure/detL.html',{'name':name,'con':con,'pass1':pass1,'id_no':id_no,'addr':addr})

def detE(request):
    name=request.POST['sname']
    con=request.POST['pnum']
    pass1=request.POST['pass1']
    eml=request.POST['emailid']
    id_no=request.POST['id_no']
    q=Employers(e_name=name,e_con_no=con,e_pass=pass1,e_mail=eml,e_id_no=id_no)
    q.save()
    return render(request,'structure/detE.html',{'name':name,'con':con,'pass1':pass1,'eml':eml,'id_no':id_no})


def dashE(request):
    usern=request.POST['uname']
    pas=request.POST['psw']
    for q in Employers.objects.all():
        if(q.e_con_no == usern and q.e_pass==pas):
            return render(request,'structure/dashE.html',{'name':q.e_name,'labour':Labours})
    messages.error(request,'Invalid')
    return render(request,'structure/login_Emp.html')



def dashL(request):
    usern=request.POST['uname']
    pas=request.POST['psw']
    for q in Labours.objects.all():
        if(q.l_con_no == usern and q.l_pass==pas):
            return render(request,'structure/dashL.html',{'name':q.l_name})
    messages.error(request,'Invalid')
    return render(request,'structure/login_Labour.html')


def find(request,name):
    n_list=[]
    addr=request.POST['locality']
    for q in Labours.objects.all():
        if(q.l_addr == addr and q.pres == 1):
            n_list.append(q)

    return render(request,'structure/dashE.html',{'n_list':n_list,'name':name,})



class FeedViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Feed.objects.all()
    serializer_class = FeedSerializer

@csrf_exempt 
def saveData(request):
    if request.method == "POST":
        received_data = json.loads(request.body)
        e_con_no=received_data.get("e_con_no")
        l_con_no=received_data.get("l_con_no")
        comment=received_data.get("comment")
        feed=Feed()
        feed.e_con_no = e_con_no
        feed.l_con_no = l_con_no
        feed.comment = comment
        feed.save()
        return HttpResponse("Your response")

account/templates/structure/dashE.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="container">

<h1>{{ name }}, Welcome to your dashboard</h1><br>
<form class="" action="{% url 'account:find' name %}" method="post">
  Enter Locality<input type="text" name="locality">
  <input type="submit" name="" value="Search">
</form>
{% if n_list %}
<table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Contact No</th>
        <th>Booking link</th>
      </tr>
    </thead>
    <tbody>
    {% for q in n_list %}
    <tr>
      <td>{{ q.l_name }}</td>
      <td>{{ q.l_con_no }}</td>
      <td><a href="#">Check details</a></td>
    </tr>
      {% endfor %}
    </tbody>
    </table>
{% else %}
{% endif %}
</body>
</html>

account/templates/structure/dashL.html
<h1><b>{{ name }}</b> Welcome to your dashboard</h1>

account/templates/structure/detE.html
<h2>Employer Details</h2>
<h3>Name:{{ name }}</h3><br>
<h3>Contact No:{{ con }}</h3><br>
<h3>Email ID:{{ eml }}</h3><br>
<h3>Password:{{ pass }}</h3><br>
<h3>ID No:{{ id_no }}</h3><br>

account/templates/structure/detL.html
<h2>Labour Details</h2>
<h3>Name:{{ name }}</h3><br>
<h3>Contact No:{{ con }}</h3><br>
<h3>Locality:{{ addr }}</h3><br>
<h3>Password:{{ pass }}</h3><br>
<h3>ID No:{{ id_no }}</h3><br>

account/templates/structure/login_Emp.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <script>
 function msg()
 {
   if ({{ flag }}==1)
   alert(Invalid);
 }
 </script>
<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
    width: 80%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
    align-items:center;
    border-radius: 15px;
}


.formEdit{
  border-radius: 25px;
  background: #73AD21;
  width: 600px;
align-items: center;

}
button {
    background-color: blue;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    align-self: center;
    border-radius: 7px;
}

body{
  background-color: white;
}
button:hover {
    opacity: 0.8;
}

.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container1 {
    padding: 16px;
}

span.psw {
    float: center;
    padding-top: 16px;

}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;

    }

}
</style>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><b>LabourHire</b></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/account/">Home</a></li>
      <li class="active"><a href="#">Contact Us</a>

      </li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Login as<span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="/account/loginL">Labour</a></li>
            <li><a href="#">Administrator</a></li>

          </ul>
        </li>
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign Up as<span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><a href="/account/signupL">Labour</a></li>
              <li><a href="/account/signupE">Employer</a></li>

            </ul>
          </li>
    </ul>
  </div>
</nav>
<div align="center">
<h2>Login Form for Employers</h2>

<form action="{% url 'account:dashE' %}" class="formEdit" method="post" autocomplete="off">
  <div class="imgcontainer">
  <center>  <img src="{% static "static_store/img_avatar2.png" %}" alt="Avatar" class="avatar"></center>
  </div>

  <div class="container1">
<div align="left">   <label for="uname"><b>Username</b></label>
<input type="text" placeholder="Enter Username" name="uname" required></div>

<div align="left">    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required></div>

<center>    <button type="submit" class="button">Login</button></center>
    <label>

<center>      <input type="checkbox" checked="checked" name="remember" style="border-radius: 5px;"> Remember me
</label></center>
<button type="button" class="button" style="background-color: red">Cancel</button>
  </div>
<center>    <span class="psw"><a href="#"><font color="#000000"><b>Forgot password?</b></font></a></span></center>
<br>
<br>
</form>
</div>
</body>
</html>

account/templates/structure/login_Labour.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
    width: 84.5%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
    align-items:center;
    border-radius: 15px;

}
body{
  background-color: #8c8c8c;
}


.formEdit{
  border-radius: 25px;
  border-color: #000000;
  background: #000000;
  width: 500px;
align-items: center;

}
button {
    background-color: #00ff00;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    align-self: center;
    border-radius: 5px;
}

button:hover {
    opacity: 0.8;
}

.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container1 {
    padding: 16px;
}

span.psw {
    float: center;
    padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }

}
</style>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><b>LabourHire</b></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/account/">Home</a></li>
      <li class="active"><a href="#">Contact Us</a>

      </li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Login as<span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="/account/loginE">Employer</a></li>
            <li><a href="#">Administrator</a></li>

          </ul>
        </li>
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign Up as<span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><a href="/account/signupL">Labour</a></li>
              <li><a href="/account/signupE">Employer</a></li>

            </ul>
          </li>
    </ul>
  </div>
</nav>
<div align="center">
  <br>
  <br>
<h2>Login Form for Labours</h2>

<form action="{% url 'account:dashL' %}" class="formEdit" method="post" autocomplete="off">


  <div class="container1">
<div align="left">   <label for="uname"><b><font color="white">Username</font></b></label>
<input type="text" placeholder="Enter Username" name="uname" required></div>

<div align="left">    <label for="psw"><b><font color="white">Password</font></b></label>
    <input type="password" placeholder="Enter Password" name="psw" required></div>

<center>    <button type="submit" class="button">Login</button></center>
    <label>
      <br>
<center>      <input type="checkbox" checked="checked" name="remember"><font color="white" style="border-radius: 5px;"> Remember me
</font></label></center>
  </div>

  <div class="container1">
   <button type="button" class="button" style="background-color: red">Cancel</button>
<center>    <span class="psw"><a href="#"><font color="white">Forgot password?</font></a></span></center>
  </div>
</form>
</div>
</body>
</html>

account/templates/structure/signup_Employer.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <script>
 function validate_form()
 {
   var name=document.forms["RegForm"]["sname"];
   var cn=document.forms["RegForm"]["pnum"];
   var eml=document.forms["RegForm"]["emailid"];
   var id_num=document.forms["RegForm"]["id_no"];
   var pass1=document.forms["RegForm"]["pass1"];
   var pass2=document.forms["RegForm"]["pass2"];
  if(eml.value.indexOf("@",0)<0)
  {
    window.alert("Please enter a valid email address.");
    eml.focus();
    return false;
  }
  if(eml.value.indexOf(".",0)<0)
  {
    alert("Please enter a valid email address.");
    eml.focus();
    return false;
  }
  if(cn.value.length != 10)
  {
  alert("Please enter a valid 10 digit phone number.");
  cn.focus();
  return false;
}
  if(pass1.value != pass2.value)
{
  alert("Passwords entered do not match.");
  pass2.focus();
  return false;
}
return true;
 }
</script>
 <style>

 body{
   background-color: #666666;
 }
 form {border: 3px solid #f1f1f1;}

 input[type=text], input[type=password] {
     width: 100%;
     padding: 12px 20px;
     margin: 8px 0;
     display: inline-block;

     box-sizing: border-box;
     align-items:center;
     border: 1px solid #d9d9d9;
     float: right;

   }
   label{
     width: 100%;
     clear: left;
     text-align: left;
     padding-left: : 15px;
     float: left;
   }

   .formEdit{


     background: hsl(345, 0%, 95%);
     width: 800px;
   align-items: center;

   }
   button {
       background-color: #009900;
       color: white;
       padding: 14px 20px;
       margin: 8px 0;
       border: none;
       cursor: pointer;
       width: 100%;
       align-self: center;
       border-radius: 5px;
   }

   button:hover {
       opacity: 0.8;
   }

   .cancelbtn {
       width: auto;
       padding: 10px 18px;
       background-color: #e60000;
   }

   .imgcontainer {
       text-align: center;
       margin: 24px 0 12px 0;
   }

   img.avatar {
       width: 40%;
       border-radius: 50%;
   }

   .container1 {
       padding: 16px;
   }

   span.psw {
       float: center;
       padding-top: 16px;
   }

  h2{
    width: 100%;
    text-align: center;
    border-bottom: 1px solid #666666;
    line-height: 0.1em;
    margin: 10px 0 20px;
  }
  h2 span{
    padding: 0 10px;
    background: hsl(345, 0%, 95%);
  }

   @media screen and (max-width: 300px) {
       span.psw {
          display: block;
          float: none;
       }

   }
 </style>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><b>LabourHire</b></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/account/">Home</a></li>
      <li class="active"><a href="#">Contact Us</a>

      </li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Login as<span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="/account/loginL">Labour</a></li>
            <li><a href="/account/loginE">Employer</a></li>
            <li><a href="#">Administrator</a></li>

          </ul>
        </li>
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign Up as<span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><a href="/account/signupL">Labour</a></li>

            </ul>
          </li>
    </ul>
  </div>
</nav>

  <div align="center">
    <br>


    <form action="{% url 'account:detE' %}" class="formEdit" onsubmit="return validate_form()" name="RegForm" method="post">
{% csrf_token %}
      <div class="container1">
        <br>
        <h2><span>Sign Up Form for Employers</span></h2>
        <br>
    <div align="left">
    <input type="text" placeholder="Enter Full Name" name="sname" required></div>

    <div align="left">
        <input type="text" placeholder="Enter Email-ID" name="emailid" required></div>

    <div align="left">
            <input type="text" placeholder="Enter Contact Number" name="pnum" required></div>

    <div align="left">
                <input type="password" placeholder="Type a Password" name="pass1" required></div>

    <div align="left">
                    <input type="password" placeholder="Type Password Again" name="pass2" required></div>

    <div align="left">    <div class="form-group">
      <select class="form-control" id="uniqueID">
        <option>Choose an ID</option>
        <option>Aadhar Card Number</option>
        <option>PAN Card Number</option>
        <option>Driving License</option>
        <option>Voting Card</option>
      </select>
    </div></div>


    <div align="left"><input type="text" name="id_no" id="id_no"></div>
    <br>
    <br>
  <center><label width="400px">      <input type="checkbox" checked="checked" name="remember" style="border-radius: 5px;"> I accept the <a href="#">Terms of Use</a> & <a href="#">Private Policy</a>
  </label></center>
<center>    <input type="submit"  value="Sign Up"></center>

<center> <button type="button" class="button" style="background-color: red">Cancel</button></center>

      </div>

        </form>
        <br>
  <center>      <label style="text-align: center;"><font color="white"> Already have an account? </font><a href="Login_Employer.html"><font color="#ffffff"><u>Login</u></font></a></label></center>
      </div>
      <br>
      <br>
      <br>
  </body>
  </html>

account/templates/structure/signup_Labour.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <script>
 function validate_form()
 {
   var name=document.forms["RegForm"]["sname"];
   var cn=document.forms["RegForm"]["pnum"];

   var id_num=document.forms["RegForm"]["id_no"];
   var pass1=document.forms["RegForm"]["pass1"];
   var pass2=document.forms["RegForm"]["pass2"];

  if(cn.value.length != 10)
  {
  alert("Please enter a valid 10 digit phone number.");
  cn.focus();
  return false;
}
  if(pass1.value != pass2.value)
{
  alert("Passwords entered do not match.");
  pass2.focus();
  return false;
}
return true;
 }
</script>
 <style>

 body{
   background-color: #666666;
 }
 form {border: 3px solid #f1f1f1;}

 input[type=text], input[type=password] {
     width: 100%;
     padding: 12px 20px;
     margin: 8px 0;
     display: inline-block;

     box-sizing: border-box;
     align-items:center;
     border: 1px solid #d9d9d9;
     float: right;

   }
   label{
     width: 100%;
     clear: left;
     text-align: left;
     padding-left: : 15px;
     float: left;
   }

   .formEdit{


     background: hsl(345, 0%, 95%);
     width: 800px;
   align-items: center;

   }
   button {
       background-color: #009900;
       color: white;
       padding: 14px 20px;
       margin: 8px 0;
       border: none;
       cursor: pointer;
       width: 100%;
       align-self: center;
       border-radius: 5px;
   }

   button:hover {
       opacity: 0.8;
   }

   .cancelbtn {
       width: auto;
       padding: 10px 18px;
       background-color: #e60000;
   }

   .imgcontainer {
       text-align: center;
       margin: 24px 0 12px 0;
   }

   img.avatar {
       width: 40%;
       border-radius: 50%;
   }

   .container1 {
       padding: 16px;
   }

   span.psw {
       float: center;
       padding-top: 16px;
   }

  h2{
    width: 100%;
    text-align: center;
    border-bottom: 1px solid #666666;
    line-height: 0.1em;
    margin: 10px 0 20px;
  }
  h2 span{
    padding: 0 10px;
    background: hsl(345, 0%, 95%);
  }

   @media screen and (max-width: 300px) {
       span.psw {
          display: block;
          float: none;
       }

   }
 </style>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><b>LabourHire</b></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/account/">Home</a></li>
      <li class="active"><a href="#">Contact Us</a>

      </li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Login as<span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="/account/loginL">Labour</a></li>
            <li><a href="/account/loginE">Employer</a></li>
            <li><a href="#">Administrator</a></li>

          </ul>
        </li>
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign Up as<span class="caret"></span></a>
          <ul class="dropdown-menu">

              <li><a href="/account/signupE">Employer</a></li>

            </ul>
          </li>
    </ul>
  </div>
</nav>

  <div align="center">
    <br>


    <form action="{% url 'account:detL' %}" class="formEdit" name="RegForm" onsubmit="return validate_form()" method="post">
{% csrf_token %}
      <div class="container1">
        <br>
        <h2><span>Sign Up Form for Labours</span></h2>
        <br>
    <div align="left">
    <input type="text" placeholder="Enter Full Name" name="sname" required></div>


    <div align="left">
            <input type="text" placeholder="Enter Contact Number" name="pnum" required></div>

    <div align="left">
            <input type="text" placeholder="Enter nearest locality" name="addr" required></div>

    <div align="left">
                <input type="password" placeholder="Type a Password" name="pass1" required></div>

    <div align="left">
                    <input type="password" placeholder="Type Password Again" name="pass2" required></div>

    <div align="left">    <div class="form-group">
      <select class="form-control" id="uniqueID" required>
        <option>Choose an ID</option>
        <option>Aadhar Card Number</option>
        <option>PAN Card Number</option>
        <option>Driving License</option>
        <option>Voting Card</option>
      </select>
    </div></div>


    <div align="left"><input type="text" name="id_no" id="id_no"></div>
    <br>
    <br>
  <center><label width="400px">      <input type="checkbox" checked="checked" name="remember" style="border-radius: 5px;"> I accept the <a href="#">Terms of Use</a> & <a href="#">Private Policy</a>
  </label></center>
<center>    <input type="submit" value="Sign Up"></center>

<center> <button type="button" class="button" style="background-color: red">Cancel</button></center>

      </div>

        </form>
        <br>
  <center>      <label style="text-align: center;"><font color="white"> Already have an account? </font><a href="Login_Employer.html"><font color="#ffffff"><u>Login</u></font></a></label></center>
      </div>
      <br>
      <br>
      <br>
  </body>
  </html>